image: node:14
variables:
  BOT_NAME: "GitLab Runner Bot"
  BOT_EMAIL: "gitlab-runner-bot@example.net"
  COMMIT_MESSAGE: "Update version"
stages:
  - test
  - lint
  - build

# Install dependencies

.lint:
  stage: lint
  tags:
    - docker
  allow_failure: false
  script:
    - cd ${DIRECTORY}
    - npm i eslint
    - node_modules/eslint/bin/eslint.js

lint_back:
  extends: .lint
  variables:
    DIRECTORY: back

lint_front:
  extends: .lint
  variables:
    DIRECTORY: front

.kaniko-build-template: &kaniko_build_definition
  image:
    name: gcr.io/kaniko-project/executor:v1.15.0-debug
    entrypoint: [""]
  tags:
    - docker
  cache: {}
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY_HOSTNAME\":{\"username\":\"$REGISTRY_USERNAME\",\"password\":\"$REGISTRY_PASSWORD\"},\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor \
        --context $CI_PROJECT_DIR/front \
        --dockerfile ${CI_PROJECT_DIR}/front/Dockerfile \
        --build-arg REACT_APP_CAS_LOGIN_URL="https://${CS_CAS_HOSTNAME}/cas/login" \
        --build-arg REACT_APP_CAS_LOGOUT_URL="https://${CS_CAS_HOSTNAME}/cas/logout" \
        --build-arg REACT_APP_CAS_LOGIN_SERVICE="/loginAccept/" \
        --build-arg REACT_APP_CAS_LOGOUT_SERVICE="/" \
        --build-arg REACT_APP_ALT_CAS_LOGIN_URL="https://${UPSACLAY_CAS_HOSTNAME}/cas/login" \
        --build-arg REACT_APP_ALT_CAS_LOGOUT_URL="https://${UPSACLAY_CAS_HOSTNAME}/cas/logout" \
        --build-arg REACT_APP_ALT_CAS_LOGIN_SERVICE="/loginAccept/" \
        --build-arg REACT_APP_ALT_CAS_LOGOUT_SERVICE="/" \
        --build-arg REACT_APP_BACK_URL="/api" \
        --build-arg REACT_APP_ALT_BACK_URL="/api" \
        --push-retry 4 \
        --destination ${REGISTRY_HOSTNAME}/resa/front:${IMAGE_VERSION} \
        --cache \
        --cache-repo ${CI_REGISTRY}/resa/github/front-cache \
        --snapshotMode=redo \
        --use-new-run=true \
        --cleanup
    - >
      /kaniko/executor \
        --context $CI_PROJECT_DIR/back \
        --dockerfile ${CI_PROJECT_DIR}/back/Dockerfile \
        --push-retry 4 \
        --destination ${REGISTRY_HOSTNAME}/resa/back:${IMAGE_VERSION} \
        --cache \
        --cache-repo ${CI_REGISTRY}/resa/github/back-cache \
        --snapshotMode=redo \
        --use-new-run=true \
        --cleanup

build-latest:
  stage: build
  <<: *kaniko_build_definition
  variables:
    IMAGE_VERSION: "latest"
  only:
    - main

build-tag:
  stage: build
  <<: *kaniko_build_definition
  variables:
    IMAGE_VERSION: "${CI_COMMIT_TAG}"
  only:
    - tags
