site_name: Resa
site_url: https://resa.centralesupelec.fr/recherche/
site_description: Plateforme pour réserver des salles sur le campus
site_author: CentraleSupélec

repo_name: CentraleSupelec/resa
repo_url: https://github.com/CentraleSupelec/resa

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - "Présentation": "index.md"
