apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.containersBack.name }}
spec:
  selector:
    matchLabels:
      app: resa-back
  {{ if not .Values.hpa.back.enabled }}
  replicas: {{ .Values.deployment.replicanb }}
  {{ end }}
  template:
    metadata:
      labels:
        app: resa-back
    spec:
      imagePullSecrets:
        - name: {{ .Values.deployment.containersBack.imagePullSecret }}
      containers:
      - name: {{ .Values.deployment.containersBack.name }}
        image: {{ .Values.deployment.containersBack.image }}
        ports:
        - containerPort: 3001
        env:
        - name: APP_ENV
          value: "{{ .Values.deployment.containersBack.appEnv }}"
        volumeMounts:
          - mountPath: /usr/src/app/src/config/secrets.json
            name: env
            subPath: .env
            readOnly: true
      volumes:
        - name: env
          secret:
            secretName: back-secrets
