{{ if .Values.hpa.front.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resa-front-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: resa-front
  minReplicas: {{ .Values.hpa.front.replicamin }}
  maxReplicas: {{ .Values.hpa.front.replicamax }}
  metrics:
    {{ if .Values.hpa.front.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.front.cpu }}
    {{ end }}
    {{ if .Values.hpa.front.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.front.memory }}
    {{ end }}
{{ end }}
