apiVersion: v1
kind: Service
metadata:
  name: resa-back-service
spec:
  selector:
    app: resa-back
  ports:
    - protocol: TCP
      port: {{ .Values.serviceBack.port }}
      targetPort: {{ .Values.serviceBack.targetPort }}
