apiVersion: v1
kind: Service
metadata:
  name: resa-front-service
spec:
  selector:
    app: resa-front
  ports:
    - protocol: TCP
      port: {{ .Values.serviceFront.port }}
      targetPort: {{ .Values.serviceFront.targetPort }}
