export const OPEN_CANCEL_MODAL = 'OPEN_CANCEL_MODAL';
export const REQUEST_CANCEL = 'REQUEST_CANCEL';
export const RECEIVE_CANCEL_CONFIRMATION = 'RECEIVE_CANCEL_CONFIRMATION';
export const RECEIVE_CANCEL_ERROR = 'RECEIVE_CANCEL_ERROR';
