export const TOGGLE_PAST_BOOKINGS = 'TOGGLE_PAST_BOOKINGS';
export const SHOW_MORE_PAST_BOOKINGS = 'SHOW_MORE_PAST_BOOKINGS';
export const INVALIDATE_BOOKINGS = 'INVALIDATE_BOOKINGS';
export const REQUEST_BOOKINGS = 'REQUEST_BOOKINGS';
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS';
export const RECEIVE_FAVORITE_ROOMS = 'RECEIVE_FAVORITE_ROOMS';
export const RECEIVE_BOOKINGS_FETCHING_ERROR = 'RECEIVE_BOOKINGS_FETCHING_ERROR';
