export const SET_ROOM_ID = 'SET_ROOM_ID';
export const REQUEST_ROOM_DETAIL = 'REQUEST_ROOM_DETAIL';
export const RECEIVE_ROOM_DETAIL = 'RECEIVE_ROOM_DETAIL';
export const RECEIVE_ROOM_DETAIL_FETCHING_ERROR = 'RECEIVE_ROOM_DETAIL_FETCHING_ERROR';
export const TOGGLE_ACTION_SELECTOR = 'TOGGLE_ACTION_SELECTOR';
export const REQUEST_ROOM_AGENDA = 'REQUEST_ROOM_AGENDA';
export const RECEIVE_ROOM_AGENDA = 'RECEIVE_ROOM_AGENDA';
export const RECEIVE_ROOM_AGENDA_FETCHING_ERROR = 'RECEIVE_ROOM_AGENDA_FETCHING_ERROR';
