export const INVALIDATE_ROOMS = 'INVALIDATE_ROOMS';
export const REQUEST_ROOMS = 'REQUEST_ROOMS';
export const RECEIVE_ROOMS = 'RECEIVE_ROOMS';
export const RECEIVE_ROOMS_FETCHING_ERROR = 'RECEIVE_ROOMS_FETCHING_ERROR';
